spring:
  application:
    name: spring
  profiles:
    active: prod

logging:
  slack:
    config: classpath:logback-spring.xml
    execution-time-log-webhook-uri: ${SLACK_EXECUTION_TIME_LOG}
    error-log-webhook-uri: ${SLACK_ERROR_LOG}